### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [carlinhoh/EDL#1]
Faltou uma análise comparativa crítica:
Como COBOL se compara a outras linguagens? (ex., em termos de legibilidade, redigibilidade e expressividade)
Justifique com argumentos.

**Comment by carlinhoh** [comment]
Professor, eu enviei meu trabalho antes do prazo de entrega e na nota está
escrito COBOL, há alguma alteração que eu deva fazer?

**Comment by fsantanna** [comment]
ok. estava esperando você responder aqui.
